apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::227892442507:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-Y4QGQCDUNTW9
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-10-26T10:23:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1029"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 970bec57-2a6c-4339-a7f0-2600a0b128ec
