apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::227892442507:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-RLQ5UTXX3OFE
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2021-10-25T15:51:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1167"
  uid: 99b66c6b-9ce7-4e47-8ca9-e18f6d9cf1a4
